[package]
name = "rgfx"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
winit = "0.30.12"
wgpu = "28.0.0"
pollster = "0.4"
bytemuck = "1.25.0"
cgmath = "0.18.0"
image = { version = "0.25.9", default-features = false, features = [ "jpeg" ] }
rand = "0.10.0"
